### ISSUE TITLE
Doesn't work on Windows

### ISSUE THREAD

**Issue by Septh** [ampproject/npw#6]
When run on Windows, `npw` exits with `ENOENT`:

```
$ npw i the-answer
node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^

Error: spawn npm ENOENT
←[90m    at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)←[39m
←[90m    at onErrorNT (node:internal/child_process:477:16)←[39m
←[90m    at processTicksAndRejections (node:internal/process/task_queues:83:21)←[39m {
  errno: ←[33m-4058←[39m,
  code: ←[32m'ENOENT'←[39m,
  syscall: ←[32m'spawn npm'←[39m,
  path: ←[32m'npm'←[39m,
  spawnargs: [ ←[32m'audit'←[39m ]
}
```

On this platform, `child_process.swpan()` should be called with the `shell` flag set, as the npm launcher actually is a `.cmd` file : https://nodejs.org/docs/latest-v16.x/api/child_process.html#spawning-bat-and-cmd-files-on-windows

I've tried setting the flag to `true` and it works nicely. However, this uses the shell defined in `%ComSpec%`, which is `cmd.exe` by default and I think most people would prefer to use some other shell (GitBash in my case). I'm not sure what the best way to handle this is, though.

**Comment by Septh** [comment]
Oh, and as a side note, the error output is broken as shown above, with color codes showing as plain text.

I don't know the reason but this can easily be worked around by outputting some text before spawning npm. This is what I used:
```diff
  if (root == null) {
    console.error('Failed to find workspace root')
    process.exit(1)
  }
+  console.log('Found workspace root at', path.relative(root, cwd) || 'current directory.')
```

Cheers and thank you for the very useful tool!

**Comment by jridgewell** [comment]
Thanks for the issue! I've only used *nix systems, so had no idea this was an issue. I'll get a bugfix shortly.
